### ISSUE TITLE
Incorrect parsing of if blocks without a semicolon

### ISSUE THREAD

**Issue by siraben** [siraben/tree-sitter-promela#3]
The following correctly parses

```pml
init {
    if 
    :: y = 3;
    fi;
    x = 3;
}
```
but this does not

```pml
init {
    if 
    :: y = 3;
    fi
    x = 3;
}
```

It appears that the `if` node did not succeed, and the partial parse for the last statement is incorrectly parsed as a variable declaration instead of an assignment.

```
(program [0, 0] - [6, 0]
  (ERROR [0, 0] - [5, 1]
    (step [2, 7] - [2, 12]
      (Stmnt [2, 7] - [2, 12]
        (assignment [2, 7] - [2, 12]
          (varref [2, 7] - [2, 8]
            (cmpnd [2, 7] - [2, 8]
              (pfld [2, 7] - [2, 8])))
          (full_expr [2, 11] - [2, 12]
            (expr [2, 11] - [2, 12]
              (const [2, 11] - [2, 12]
                (number [2, 11] - [2, 12])))))))
    (step [3, 4] - [4, 9]
      (one_decl [3, 4] - [4, 9]
        (var_list [4, 4] - [4, 9]
          (ivar [4, 4] - [4, 9]
            (vardcl [4, 4] - [4, 5]
              (uname [4, 4] - [4, 5]))
            (expr [4, 8] - [4, 9]
              (const [4, 8] - [4, 9]
                (number [4, 8] - [4, 9])))))))))
```

**Comment by siraben** [comment]
This could result from the `one_decl` rule being too highly prioritized. The partial parse tree reads something like `<type> x = 3;`

**Comment by siraben** [comment]
@nimble-code are semicolons optional at the end of if blocks? In the grammar it seems that if there are 2 or more statements there must be a semicolon separating them (the last being optional.)

**Comment by nimble-code** [comment]
interesting case -- it does look like the parser expects a semi-colon after the fi, but it shouldn't

**Comment by siraben** [comment]
As far as I can tell from the Spin examples, there isn't an instance where the if block has a semicolon omitted, so I think this code is invalid:

```pml
init {
    if 
    :: y = 3;
    fi
    x = 3;
}
```

**Comment by nimble-code** [comment]
I'll see if I can fix it, to make semi-colons optional there, but for the time being this will have to be the work-around

**Comment by siraben** [comment]
@nimble-code Ok, thanks. Please note that this repository is a re-implementation of the Promela grammar in tree-sitter and I'm taking the YACC grammar as the source of ground truth to replicate. Is there a way to only run the parser in Spin?

**Comment by nimble-code** [comment]
> 

I just tried this example, but it parses correctly on my system (Spin version 6.5.1 from 3 june 2021)
int x, y
init {
    if 
    :: y = 3;
    fi
    x = 3;
}

same result if the remaining two semi-colons are also deleted

**Comment by nimble-code** [comment]
by the way, in the spin parser, "missing" semi-colons are reinserted into the token stream in the lexer, so that the parser (following the yacc grammar) doesn't need to worry about it

**Comment by siraben** [comment]
@nimble-code I see, under what conditions is the semicolon inserted?

**Comment by nimble-code** [comment]
at the end of a line, if the preceding statement didn't have a semi-colon
(tricky in conditions that are split across multiple lines...)
